"""Tercera migracion

Revision ID: 2d3fa6c2205f
Revises: a079c3180810
Create Date: 2025-05-18 21:21:05.787374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3fa6c2205f'
down_revision: Union[str, None] = 'a079c3180810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cursos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('docente_materia', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('docente_materia', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('docentes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('docentes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('estudiantes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('estudiantes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('materias', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('materias', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materias', 'updated_at')
    op.drop_column('materias', 'created_at')
    op.drop_column('estudiantes', 'updated_at')
    op.drop_column('estudiantes', 'created_at')
    op.drop_column('docentes', 'updated_at')
    op.drop_column('docentes', 'created_at')
    op.drop_column('docente_materia', 'updated_at')
    op.drop_column('docente_materia', 'created_at')
    op.drop_column('cursos', 'updated_at')
    op.drop_column('cursos', 'created_at')
    # ### end Alembic commands ###
