"""Segunda migracion

Revision ID: 7590157ec052
Revises: 0c9e1534dce8
Create Date: 2025-06-02 09:37:08.601523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7590157ec052'
down_revision: Union[str, None] = '0c9e1534dce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediccion_rendimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promedio_notas', sa.Float(), nullable=False),
    sa.Column('porcentaje_asistencia', sa.Float(), nullable=False),
    sa.Column('promedio_participacion', sa.Float(), nullable=False),
    sa.Column('resultado_numerico', sa.Float(), nullable=False),
    sa.Column('clasificacion', sa.String(), nullable=False),
    sa.Column('fecha_generada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediccion_rendimiento_id'), 'prediccion_rendimiento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediccion_rendimiento_id'), table_name='prediccion_rendimiento')
    op.drop_table('prediccion_rendimiento')
    # ### end Alembic commands ###
