"""Tercera migracion

Revision ID: 9c240cd20e53
Revises: 2d3fa6c2205f
Create Date: 2025-05-18 21:26:40.702090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c240cd20e53'
down_revision: Union[str, None] = '2d3fa6c2205f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('turno', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'turno')
    # ### end Alembic commands ###
