"""Quinta migracion

Revision ID: e7ecec316b45
Revises: 5b37869211ed
Create Date: 2025-05-18 22:11:22.954609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ecec316b45'
down_revision: Union[str, None] = '5b37869211ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_index(op.f('ix_gestiones_id'), 'gestiones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gestiones_id'), table_name='gestiones')
    op.drop_table('gestiones')
    # ### end Alembic commands ###
